training_params:
  num_epochs: 5
  batch_size: 64
  learning_rate: 0.001
  num_workers: 4

models:
  - _target_: src.models.MNIST3dModelBuilder
  - _target_: src.models.MNIST3dModelBuilder
  - _target_: src.models.MNIST3dModelBuilder
  - _target_: src.models.MNIST3dModelBuilder
  - _target_: src.models.MNIST3dModelBuilder
  - _target_: src.models.MNIST3dModelBuilder
