exp_name: "exp4_nodule"
dataset: "NoduleMNIST3D"

training_params:
  num_epochs: 500
  batch_size: 64
  learning_rate: 0.0005
  num_workers: 8

model:
  - _target_: src.models.MNIST3dCNNExp4N1
  - _target_: src.models.MNIST3dLiqExp4N2
  - _target_: src.models.MNIST3dCNNExp4N3
  - _target_: src.models.MNIST3dCNNExp4N4
  - _target_: src.models.MNIST3dLiqExp4N5
  - _target_: src.models.MNIST3dLiqExp4N6
