from src.models.lungtissues.cnn_baseline import CNNBaseline
from src.models.lungtissues.cnn_baseline_dropout import CNNBaselineDropout
from src.models.lungtissues.cnn_baseline_large import CNNBaselineLarge
from src.models.lungtissues.cnn_baseline_small import CNNBaselineSmall
from src.models.lungtissues.cnn_baseline_very_small import CNNBaselineVerySmall
from src.models.mnist3d.mnist_exp1 import *
from src.models.mnist3d.mnist_exp2 import *
from src.models.mnist3d.mnist_exp3 import *
from src.models.mnist3d.mnist_exp4 import *