from src.models.lungtissues.cnn_baseline import CNNBaseline
from src.models.lungtissues.cnn_baseline_dropout import CNNBaselineDropout
from src.models.lungtissues.cnn_baseline_large import CNNBaselineLarge
from src.models.lungtissues.cnn_baseline_small import CNNBaselineSmall
from src.models.lungtissues.cnn_baseline_very_small import CNNBaselineVerySmall
from src.models.mnist2d.mnist_cnn_baseline import MNIST2dCNNBaseline
from src.models.mnist2d.mnist_cnn_baseline_exp0 import MNIST2dCNNBaselineExp0
from src.models.mnist2d.mnist_cnn_with_1_liquid import MNIST2dCNNWith1Liquid
from src.models.mnist2d.mnist_linear_baseline import MNIST2dLinearBaseline
from src.models.mnist2d.mnist_liquid_baseline import MNIST2dLiquidBaseline
from src.models.mnist2d.mnist_liquid_baseline_exp0 import MNIST2dLiquidBaselineExp0
from src.models.mnist2d.mnist_lstm_baseline import MNIST2dLSTMBaseline
from src.models.mnist3d.mnist_cnn_baseline import MNIST3dCNNBaseline
from src.models.mnist3d.mnist_full_liquid_baseline import MNIST3dFullLiquidBaseline
from src.models.mnist3d.mnist_liquid_baseline import MNIST3dLiquidBaseline
from src.models.mnist3d.mnist_full_liquid_conf import MNIST3dFullLiquidConf0, MNIST3dFullLiquidConf1, MNIST3dFullLiquidConf2, MNIST3dFullLiquidConf3, MNIST3dFullLiquidConf4, MNIST3dFullLiquidConf5