from src.models.cnn_baseline import CNNBaseline
from src.models.mnist_cnn_baseline import MNISTCNNBaseline
from src.models.mnist_liquid_baseline import MNISTLiquidBaseline
from src.models.mnist_lstm_baseline import MNISTLSTMBaseline